language: node_js
node_js:
  - '8'

os: linux

env:
  - ESLINT_VERSION=4

matrix:
  include:
  - os: osx
    env: ESLINT_VERSION=4
    node_js: 8

before_install:
  - nvm install-latest-npm
  - 'if [ -n "${PACKAGE-}" ]; then cd "${PACKAGE}"; fi'

install:
  - npm install
  - npm install --no-save eslint@$ESLINT_VERSION --ignore-scripts || true

script:
  - npm run lint
  - npm test

after_success: npm run coverage
